services:
  express:
    build: ./express
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.express.rule=Host(`openaiua.cloud`)"
      - "traefik.http.routers.express.entrypoints=web,websecure"
      - "traefik.http.routers.express.tls.certresolver=mytlschallenge"
      - "traefik.http.services.express.loadbalancer.server.port=3000"
    networks:
      - llm-network
    expose:
      - "3000"

networks:
  llm-network:
    driver: bridge
